'use client';

import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ExternalLink, MessageSquare, TrendingUp, User, Calendar } from "lucide-react";
import { formatDistanceToNow } from "date-fns";

interface RedditPost {
  reddit_id: string;
  subreddit: string;
  title: string;
  content: string | null;
  url: string | null;
  score: number;
  comments: number;
  author: string;
  created_utc: string;
}

interface RedditSourcesProps {
  sources: RedditPost[];
  title?: string;
}

export function RedditSources({ sources, title = "Reddit Sources" }: RedditSourcesProps) {
  if (sources.length === 0) {
    return null;
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        <div className="w-6 h-6 bg-orange-500 rounded-full flex items-center justify-center">
          <span className="text-white text-xs font-bold">r</span>
        </div>
        <h3 className="text-lg font-semibold">{title}</h3>
        <Badge variant="secondary" className="bg-orange-50 text-orange-700">
          {sources.length} {sources.length === 1 ? 'source' : 'sources'}
        </Badge>
      </div>

      <div className="space-y-3">
        {sources.map((post) => (
          <Card key={post.reddit_id} className="border border-orange-100 hover:border-orange-200 transition-colors">
            <CardHeader className="pb-2">
              <div className="flex items-start justify-between gap-2">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2">
                    <Badge variant="outline" className="text-xs">
                      r/{post.subreddit}
                    </Badge>
                    <div className="flex items-center gap-1 text-xs text-muted-foreground">
                      <User className="w-3 h-3" />
                      <span>u/{post.author}</span>
                    </div>
                    <div className="flex items-center gap-1 text-xs text-muted-foreground">
                      <Calendar className="w-3 h-3" />
                      <span>{formatDistanceToNow(new Date(post.created_utc), { addSuffix: true })}</span>
                    </div>
                  </div>
                  <h4 className="font-medium text-sm line-clamp-2 leading-tight">
                    {post.title}
                  </h4>
                </div>
                {post.url && (
                  <a
                    href={post.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="shrink-0 p-1 hover:bg-orange-50 rounded transition-colors"
                    title="View on Reddit"
                  >
                    <ExternalLink className="w-4 h-4 text-orange-600" />
                  </a>
                )}
              </div>
            </CardHeader>

            <CardContent className="pt-0">
              {post.content && (
                <p className="text-xs text-muted-foreground line-clamp-2 mb-3 leading-relaxed">
                  {post.content}
                </p>
              )}

              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <div className="flex items-center gap-1">
                  <TrendingUp className="w-3 h-3" />
                  <span>{post.score} upvotes</span>
                </div>
                <div className="flex items-center gap-1">
                  <MessageSquare className="w-3 h-3" />
                  <span>{post.comments} comments</span>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="text-xs text-muted-foreground bg-orange-50 p-3 rounded-md border border-orange-100">
        💡 This startup idea was generated by analyzing pain points and problems discussed in these Reddit posts.
      </div>
    </div>
  );
}