import OpenAI from 'openai'
import type { RedditContact } from '@/types/supabase'
import { log } from '@/lib/logger'
import {
  type TemplateVariant,
  TEMPLATE_VARIANT_CONFIGS,
  getRandomTemplateVariant,
} from '@/lib/constants/template-variants'

/**
 * Epic 2, Story 2.3 & 2.10: AI Message Templates with A/B Testing
 *
 * Generates personalized message templates using GPT-4 based on:
 * - Contact's Reddit post excerpt
 * - Pain point details
 * - Template variant (professional, casual, concise, value_first)
 * - Random variant assignment for A/B testing
 */

interface GenerateTemplateParams {
  contact: RedditContact
  painPointTitle: string
  painPointContent: string | null
  variant: TemplateVariant
}

interface GenerateTemplateResult {
  success: boolean
  template?: string
  tokensUsed?: number
  error?: string
}

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
})

/**
 * Get variant-specific system prompt from configuration
 */
function getVariantSystemPrompt(variant: TemplateVariant): string {
  const config = TEMPLATE_VARIANT_CONFIGS[variant]
  return config.systemPrompt
}

/**
 * Generate a personalized message template using GPT-4
 */
export async function generateMessageTemplate(
  params: GenerateTemplateParams
): Promise<GenerateTemplateResult> {
  try {
    const { contact, painPointTitle, painPointContent, variant } = params

    // Get variant-specific system prompt
    const variantPrompt = getVariantSystemPrompt(variant)

    const systemPrompt = `You are an expert at writing personalized, empathetic outreach messages for founders reaching out to potential customers on Reddit.

Your goal: Write a message that feels PERSONAL, not salesy. Show genuine understanding of their problem. Offer value, not a pitch.

${variantPrompt}

Additional guidelines:
- Reference their specific Reddit post to show you read it
- Demonstrate empathy for their pain point
- Keep it conversational and human (not corporate)
- DO NOT include subject line
- DO NOT include salutation like "Dear" or "Hi [Name]" - the message should start directly
- DO NOT sign off with your name - just end with the message`

    // Construct the user prompt with context
    const userPrompt = `Context:
- Pain Point: "${painPointTitle}"
${painPointContent ? `- Full Context: "${painPointContent.substring(0, 500)}"` : ''}
- Reddit User: u/${contact.reddit_username}
- Their Post Excerpt: "${contact.post_excerpt}"
- Their Karma: ${contact.karma}
- Account Age: ${contact.account_age_days} days

Write a personalized Reddit DM for this user. Reference their specific post excerpt to show you actually read what they wrote. Be genuinely helpful, not salesy.`

    // Call OpenAI GPT-4
    const completion = await openai.chat.completions.create({
      model: 'gpt-4-turbo-preview',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature: 0.8, // Slightly higher for more creative, personalized responses
      max_tokens: 400,
      top_p: 0.9
    })

    const template = completion.choices[0]?.message?.content?.trim()

    if (!template) {
      return {
        success: false,
        error: 'No template generated by AI'
      }
    }

    return {
      success: true,
      template,
      tokensUsed: completion.usage?.total_tokens || 0
    }
  } catch (error) {
    log.error('[template-generator] Error generating template:', error)
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error generating template'
    }
  }
}

/**
 * Generate a template with randomly assigned variant for A/B testing
 * Returns both the template and the variant used
 */
export async function generateTemplateWithRandomVariant(
  params: Omit<GenerateTemplateParams, 'variant'>
): Promise<GenerateTemplateResult & { variant: TemplateVariant }> {
  const variant = getRandomTemplateVariant()
  const result = await generateMessageTemplate({ ...params, variant })

  return {
    ...result,
    variant,
  }
}

/**
 * Generate multiple template variants for comparison/testing
 */
export async function generateMultipleTemplates(
  params: Omit<GenerateTemplateParams, 'variant'>
): Promise<Record<TemplateVariant, GenerateTemplateResult>> {
  const variants: TemplateVariant[] = ['professional', 'casual', 'concise', 'value_first']

  const results = await Promise.all(
    variants.map(variant =>
      generateMessageTemplate({ ...params, variant })
    )
  )

  return {
    professional: results[0],
    casual: results[1],
    concise: results[2],
    value_first: results[3]
  }
}

/**
 * Estimate cost of template generation
 * GPT-4 Turbo pricing: $0.01 per 1K input tokens, $0.03 per 1K output tokens
 */
export function estimateTemplateCost(tokensUsed: number): number {
  // Rough estimate: ~500 input tokens, ~250 output tokens per template
  const avgInputTokens = 500
  const avgOutputTokens = 250

  const inputCost = (avgInputTokens / 1000) * 0.01
  const outputCost = (avgOutputTokens / 1000) * 0.03

  return inputCost + outputCost // ~$0.0125 per template
}
